"""Survey response schemas."""
from pydantic import BaseModel, Field, ConfigDict
from typing import Optional, List, Dict, Any
from datetime import datetime


class QuestionAnswerCreate(BaseModel):
    """Create question answer."""
    question_id: int
    answer_value: Optional[Any] = None
    media_url: Optional[str] = None
    answered_at: datetime


class SurveyResponseCreate(BaseModel):
    """Create survey response (offline sync)."""
    client_id: str = Field(..., description="UUID generated by mobile app")
    version_id: int
    location: Optional[Dict[str, Any]] = None
    started_at: Optional[datetime] = None
    completed_at: datetime
    device_info: Optional[Dict[str, Any]] = None
    answers: List[QuestionAnswerCreate] = Field(..., min_length=1)


class QuestionAnswerResponse(BaseModel):
    """Question answer response."""
    id: int
    question_id: int
    answer_value: Optional[Any] = None
    media_url: Optional[str] = None
    answered_at: datetime
    
    model_config = ConfigDict(from_attributes=True)


class SurveyResponseDetail(BaseModel):
    """Detailed survey response."""
    id: int
    user_id: int
    version_id: int
    client_id: str
    location: Optional[Dict[str, Any]] = None
    started_at: Optional[datetime] = None
    completed_at: datetime
    synced_at: datetime
    device_info: Optional[Dict[str, Any]] = None
    answers: List[QuestionAnswerResponse] = []
    
    model_config = ConfigDict(from_attributes=True)
