"""fix_assignments_enum_values_callable

Revision ID: 14327940206c
Revises: 19fa2c3881ea
Create Date: 2026-02-17 22:58:29.346425

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '14327940206c'
down_revision = '19fa2c3881ea'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
