"""assignments_add_notes_fix_assigned_by_fk_drop_unique

Revision ID: a7fbfc7391ce
Revises: d4e5f6a7b8c9
Create Date: 2026-02-17 21:59:18.383254

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a7fbfc7391ce'
down_revision = 'd4e5f6a7b8c9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_notifications_read_created', table_name='notifications')
    op.drop_index('ix_notifications_id', table_name='notifications')
    op.drop_table('notifications')
    op.add_column('assignments', sa.Column('notes', sa.Text(), nullable=True))
    op.alter_column('assignments', 'assigned_by',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint('uq_user_survey', 'assignments', type_='unique')
    op.create_index(op.f('ix_assignments_assigned_by'), 'assignments', ['assigned_by'], unique=False)
    op.create_foreign_key(None, 'assignments', 'users', ['assigned_by'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'assignments', type_='foreignkey')
    op.drop_index(op.f('ix_assignments_assigned_by'), table_name='assignments')
    op.create_unique_constraint('uq_user_survey', 'assignments', ['user_id', 'survey_id'])
    op.alter_column('assignments', 'assigned_by',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('assignments', 'notes')
    op.create_table('notifications',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('message', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('read', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('action_url', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='notifications_pkey')
    )
    op.create_index('ix_notifications_id', 'notifications', ['id'], unique=False)
    op.create_index('idx_notifications_read_created', 'notifications', ['read', sa.text('created_at DESC')], unique=False)
    # ### end Alembic commands ###
