"""Add activation system tables

Revision ID: d56fad6cd7db
Revises: 5acd0fab379c
Create Date: 2026-02-15 20:25:55.156375

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd56fad6cd7db'
down_revision = '5acd0fab379c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_whitelist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('identifier', sa.String(length=255), nullable=False),
    sa.Column('identifier_type', sa.String(length=20), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('assigned_role', sa.String(length=20), nullable=False),
    sa.Column('assigned_supervisor_id', sa.Integer(), nullable=True),
    sa.Column('is_activated', sa.Boolean(), nullable=False),
    sa.Column('activated_user_id', sa.Integer(), nullable=True),
    sa.Column('activated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.CheckConstraint("assigned_role IN ('admin', 'encargado', 'brigadista')", name='check_assigned_role'),
    sa.CheckConstraint("identifier_type IN ('email', 'phone', 'national_id')", name='check_identifier_type'),
    sa.CheckConstraint('\n            (is_activated = TRUE AND activated_user_id IS NOT NULL AND activated_at IS NOT NULL)\n            OR (is_activated = FALSE AND activated_user_id IS NULL AND activated_at IS NULL)\n            ', name='check_activated_consistency'),
    sa.ForeignKeyConstraint(['activated_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['assigned_supervisor_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_whitelist_activated_user_id'), 'user_whitelist', ['activated_user_id'], unique=False)
    op.create_index(op.f('ix_user_whitelist_assigned_supervisor_id'), 'user_whitelist', ['assigned_supervisor_id'], unique=False)
    op.create_index(op.f('ix_user_whitelist_created_by'), 'user_whitelist', ['created_by'], unique=False)
    op.create_index(op.f('ix_user_whitelist_id'), 'user_whitelist', ['id'], unique=False)
    op.create_index(op.f('ix_user_whitelist_identifier'), 'user_whitelist', ['identifier'], unique=True)
    op.create_index(op.f('ix_user_whitelist_is_activated'), 'user_whitelist', ['is_activated'], unique=False)
    op.create_table('activation_codes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code_hash', sa.String(length=60), nullable=False),
    sa.Column('whitelist_id', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_used', sa.Boolean(), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('used_by_user_id', sa.Integer(), nullable=True),
    sa.Column('activation_attempts', sa.Integer(), nullable=False),
    sa.Column('last_attempt_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_attempt_ip', sa.String(length=45), nullable=True),
    sa.Column('generated_by', sa.Integer(), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('\n            (is_used = TRUE AND used_at IS NOT NULL AND used_by_user_id IS NOT NULL)\n            OR (is_used = FALSE AND used_at IS NULL AND used_by_user_id IS NULL)\n            ', name='check_used_consistency'),
    sa.CheckConstraint('activation_attempts >= 0', name='check_attempts_positive'),
    sa.CheckConstraint('expires_at > generated_at', name='check_expires_future'),
    sa.ForeignKeyConstraint(['generated_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['used_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['whitelist_id'], ['user_whitelist.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_activation_codes_activation_attempts'), 'activation_codes', ['activation_attempts'], unique=False)
    op.create_index(op.f('ix_activation_codes_code_hash'), 'activation_codes', ['code_hash'], unique=False)
    op.create_index(op.f('ix_activation_codes_expires_at'), 'activation_codes', ['expires_at'], unique=False)
    op.create_index(op.f('ix_activation_codes_id'), 'activation_codes', ['id'], unique=False)
    op.create_index(op.f('ix_activation_codes_is_used'), 'activation_codes', ['is_used'], unique=False)
    op.create_index(op.f('ix_activation_codes_whitelist_id'), 'activation_codes', ['whitelist_id'], unique=False)
    op.create_table('activation_audit_log',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('activation_code_id', sa.Integer(), nullable=True),
    sa.Column('whitelist_id', sa.Integer(), nullable=True),
    sa.Column('identifier_attempted', sa.String(length=255), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=False),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('device_id', sa.String(length=255), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('failure_reason', sa.String(length=255), nullable=True),
    sa.Column('created_user_id', sa.Integer(), nullable=True),
    sa.Column('request_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("\n            event_type IN (\n                'code_generated',\n                'code_validation_attempt',\n                'code_validation_success',\n                'activation_attempt',\n                'activation_success',\n                'activation_failed',\n                'code_expired',\n                'code_locked',\n                'code_revoked',\n                'rate_limit_exceeded'\n            )\n            ", name='check_event_type'),
    sa.ForeignKeyConstraint(['activation_code_id'], ['activation_codes.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['whitelist_id'], ['user_whitelist.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_activation_audit_log_created_at'), 'activation_audit_log', ['created_at'], unique=False)
    op.create_index(op.f('ix_activation_audit_log_id'), 'activation_audit_log', ['id'], unique=False)
    op.create_index(op.f('ix_activation_audit_log_ip_address'), 'activation_audit_log', ['ip_address'], unique=False)
    op.create_index(op.f('ix_activation_audit_log_success'), 'activation_audit_log', ['success'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_activation_audit_log_success'), table_name='activation_audit_log')
    op.drop_index(op.f('ix_activation_audit_log_ip_address'), table_name='activation_audit_log')
    op.drop_index(op.f('ix_activation_audit_log_id'), table_name='activation_audit_log')
    op.drop_index(op.f('ix_activation_audit_log_created_at'), table_name='activation_audit_log')
    op.drop_table('activation_audit_log')
    op.drop_index(op.f('ix_activation_codes_whitelist_id'), table_name='activation_codes')
    op.drop_index(op.f('ix_activation_codes_is_used'), table_name='activation_codes')
    op.drop_index(op.f('ix_activation_codes_id'), table_name='activation_codes')
    op.drop_index(op.f('ix_activation_codes_expires_at'), table_name='activation_codes')
    op.drop_index(op.f('ix_activation_codes_code_hash'), table_name='activation_codes')
    op.drop_index(op.f('ix_activation_codes_activation_attempts'), table_name='activation_codes')
    op.drop_table('activation_codes')
    op.drop_index(op.f('ix_user_whitelist_is_activated'), table_name='user_whitelist')
    op.drop_index(op.f('ix_user_whitelist_identifier'), table_name='user_whitelist')
    op.drop_index(op.f('ix_user_whitelist_id'), table_name='user_whitelist')
    op.drop_index(op.f('ix_user_whitelist_created_by'), table_name='user_whitelist')
    op.drop_index(op.f('ix_user_whitelist_assigned_supervisor_id'), table_name='user_whitelist')
    op.drop_index(op.f('ix_user_whitelist_activated_user_id'), table_name='user_whitelist')
    op.drop_table('user_whitelist')
    # ### end Alembic commands ###
